"""
Empirical prior: P(rank R appears in a competent player's 4-card keep | dealt).

Used by LeifV3Bot to seed P(opp_has(c)) at start of pegging. Run once;
paste the printed dict into leifv3_bot.py.

The "competent player" we model is LeifV2Bot — the strongest discard
we have. Dealer-ness is sampled uniformly because LeifV2's discard
behavior depends on it (crib EV sign).
"""

import os
import random
import sys
from collections import Counter

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "src")))

from cribbage.bots.leifv2_bot import LeifV2Bot
from cribbage.models import Card, Rank, Suit

NUM_TRIALS = 10_000


def main():
    rng = random.Random(0)
    full_deck = [Card(r, s) for r in Rank for s in Suit]
    bot = LeifV2Bot("prior_builder")

    dealt = Counter()
    kept = Counter()

    for i in range(NUM_TRIALS):
        if i % 1000 == 0 and i > 0:
            print(f"  trial {i}/{NUM_TRIALS}", file=sys.stderr)
        hand = rng.sample(full_deck, 6)
        is_dealer = rng.random() < 0.5
        thrown = bot.discard(list(hand), is_dealer=is_dealer)
        thrown_set = set(thrown)
        keep = [c for c in hand if c not in thrown_set]

        for c in hand:
            dealt[c.rank] += 1
        for c in keep:
            kept[c.rank] += 1

    print()
    print("# Empirical P(rank kept | dealt) over", NUM_TRIALS, "trials")
    print("# Generated by scratch/build_keep_prior.py")
    print("_KEEP_PRIOR = {")
    for r in Rank:
        p = kept[r] / dealt[r] if dealt[r] else 0.0
        print(f"    Rank.{r.name}: {p:.4f},  # n_dealt={dealt[r]}")
    print("}")


if __name__ == "__main__":
    main()
