"""
LeifV3Bot — V2 discard + belief-driven 1-ply pegging.

Tracks P(opp_has(c)) for every unseen card. Updates as cards appear in
peg_history and when opp is forced to say "Go".

Pegging policy: pick the card c maximizing
    score_pegging(history + [c])  -  sum_u P(opp_has(u)) * score_pegging(history + [c, u])
where the sum is over unseen cards u that opp could legally play next
(new_count + u.value <= 31). If opp is forced to Go, treat danger as -1
(the Go point we'll score).

Belief representation is per-card marginal — fast, transparent, but
correlation-blind. Acceptable trade-off for v3.
"""

from typing import Dict, List, Optional, Tuple

from ..models import Card, Rank, Suit
from ..rules import score_pegging
from .leifv2_bot import LeifV2Bot


# Empirical P(rank kept | dealt) over 10000 trials. Generated by
_KEEP_PRIOR = {
    Rank.ACE: 0.6284,
    Rank.TWO: 0.6424,
    Rank.THREE: 0.6805,
    Rank.FOUR: 0.7414,
    Rank.FIVE: 0.8479,
    Rank.SIX: 0.7001,
    Rank.SEVEN: 0.6203,
    Rank.EIGHT: 0.6061,
    Rank.NINE: 0.6388,
    Rank.TEN: 0.6522,
    Rank.JACK: 0.7190,
    Rank.QUEEN: 0.6265,
    Rank.KING: 0.5617,
}


class LeifV3Bot(LeifV2Bot):
    def __init__(self, player_id: str):
        super().__init__(player_id)
        self._reset_round_state()

    def reset(self):
        self._reset_round_state()

    def _reset_round_state(self):
        self._my_dealt: set = set()
        self._my_kept: set = set()
        self._played_by_me: set = set()
        self._absorbed: set = set()
        self._opp_played_count = 0
        self._p_opp: Dict[Card, float] = {}

    def discard(self, hand: List[Card], is_dealer: bool) -> Tuple[Card, Card]:
        self._reset_round_state()
        self._my_dealt = set(hand)

        thrown = super().discard(hand, is_dealer)
        thrown_set = set(thrown)
        self._my_kept = self._my_dealt - thrown_set

        # Seed P(opp_has(c)) over the 46 unseen cards using the empirical
        # keep-prior. Sum scaled to 4 (opp has 4 cards).
        full_deck = [Card(r, s) for r in Rank for s in Suit]
        unseen = [c for c in full_deck if c not in self._my_dealt]
        weights = {c: _KEEP_PRIOR[c.rank] for c in unseen}
        total = sum(weights.values())
        if total > 0:
            scale = 4.0 / total
            self._p_opp = {c: min(w * scale, 1.0) for c, w in weights.items()}
        else:
            self._p_opp = {c: 4.0 / len(unseen) for c in unseen}

        return thrown

    def _renormalize(self) -> None:
        """Scale positive marginals so they sum to (4 - opp_played), capped at 1.0."""
        target = 4.0 - self._opp_played_count
        if target <= 0:
            return
        current = sum(p for p in self._p_opp.values() if p > 0)
        if current <= 0:
            return
        scale = target / current
        for c in list(self._p_opp.keys()):
            p = self._p_opp[c]
            if p > 0:
                np = p * scale
                if np > 1.0:
                    np = 1.0
                self._p_opp[c] = np

    def peg(self, hand: List[Card], peg_history: List[Card], current_count: int) -> Optional[Card]:
        # Belief update: cards I played since last call.
        hand_set = set(hand)
        new_self_plays = (self._my_kept - hand_set) - self._played_by_me
        self._played_by_me |= new_self_plays
        self._absorbed |= new_self_plays

        # Belief update: opp plays appearing in peg_history.
        new_opp_plays = 0
        for c in peg_history:
            if c in self._absorbed:
                continue
            self._absorbed.add(c)
            if c in self._played_by_me:
                continue
            new_opp_plays += 1
            self._opp_played_count += 1
            if c in self._p_opp:
                self._p_opp[c] = 0.0
        if new_opp_plays > 0:
            self._renormalize()

        # Go inference: if the last card in peg_history is mine, opp said Go
        # between my plays. At the current count, opp has no card with
        # value <= (31 - current_count).
        if peg_history and current_count > 0 and peg_history[-1] in self._played_by_me:
            threshold = 31 - current_count
            changed = False
            for c, p in self._p_opp.items():
                if p > 0 and c.value <= threshold:
                    self._p_opp[c] = 0.0
                    changed = True
            if changed:
                self._renormalize()

        legal = [c for c in hand if current_count + c.value <= 31]
        if not legal:
            return None

        best_card: Optional[Card] = None
        best_net = float("-inf")

        for c in legal:
            my_score, _ = score_pegging(peg_history + [c])
            new_count = current_count + c.value

            if new_count == 31:
                expected_danger = 0.0
            else:
                expected_danger = 0.0
                opp_can_play = False
                for u, p in self._p_opp.items():
                    if p <= 0:
                        continue
                    if new_count + u.value > 31:
                        continue
                    opp_can_play = True
                    opp_pts, _ = score_pegging(peg_history + [c, u])
                    expected_danger += p * opp_pts
                if not opp_can_play:
                    expected_danger = -1.0

            net = my_score - expected_danger

            if net > best_net:
                best_net = net
                best_card = c
            elif net == best_net and best_card is not None and c.value > best_card.value:
                best_card = c

        return best_card
